#!/usr/bin/env bash
cd "$(dirname "${BASH_SOURCE[0]}")"

function ok() {
    scp -qF ./ssh.config ./host/* root@sshfs:/usr/local/bin/
    ./sshfs echo ok
}

mkdir -p /data/.ssh

[[ -f /data/.ssh/id_rsa ]] && ok && exit

ssh-keygen -t rsa -b 4096 -C "sshfs-admin" -f /data/.ssh/id_rsa -q -N ""
cat /data/.ssh/id_rsa.pub >> /data/sshfs/etc/root.ssh/authorized_keys

ok
