#!/usr/bin/env bash
USERNAME=$1
DEPT=$2
PUB_KEY=${3:-$(cat "/data/users/${USERNAME}/.ssh/authorized_keys" 2>/dev/null)}

id -u "${USERNAME}" > /dev/null 2>&1 || { echo User \"${USERNAME}\" does not exists; exit; }

ls "/data/depts/${DEPT}" > /dev/null 2>&1 || { echo Department \"${DEPT}\" does not exist; exit; }
sf_user_add "${USERNAME}" "${DEPT}" "${PUB_KEY}"
echo ok
